### ISSUE TITLE
Add Github label: Torchsharp

### ISSUE THREAD

**Issue by GeorgeS2019** [ErrorGz/ImageProcess#1]
Add Github label: Torchsharp

![image](https://github.com/ds5678/TorchCategorizationDemo/assets/49812372/6323b634-2247-4be6-9ebf-66c0d927590d)

**Comment by ErrorGz** [comment]
> Add Github label: Torchsharp
> 
> ![image](https://user-images.githubusercontent.com/49812372/273437226-6323b634-2247-4be6-9ebf-66c0d927590d.png)

Thank you for your kind reminder. May I ask if you are referring to making the modification in the readme.txt file? Thank you.

**Comment by GeorgeS2019** [comment]
Not readne, GitHub label or topic
